name: Build and Deploy Docusaurus

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use the Node.js version recommended by Docusaurus

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Docusaurus site
    - name: Build the Site
      run: npm run build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
